name: "C++ CI"

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          sudo apt install cmake
          sudo apt install g++-12
          sudo apt install libgtest-dev
          cmake .
          cmake --build .
      - name: test
        run: |
          ctest -rerun-failed --output-on-failure
